### ISSUE TITLE
Reply to NFS-Client package

### ISSUE THREAD

**Issue by SonnyX** [jchristn/jchristn#1]
Hi there,

Replying here as my mail fails to deliver (due to something on my side):

Since it's been forked from nekodrive, it follows the same license, which is lgpl-3.0, as for the GetItemList() not seemingly working, I'm afraid you'll have to do a bit of debugging yourself. Unless what you're asking me for is a tree, in that case you should be able to iterate over the resultset of GetItemList(), and then call IsDirectory() on the items of the resultset and incase true, call getItemList on that subdirectory again to make a recursive call.

As for the API, I believe GetItemList takes relative paths, where the best way to figure out where you start when you connect to the server is by specifying the path '.' (a singular dot, for the current directory)

It's been a while, and the code is not (nor will be) actively maintained by me. Although I'm always open for reviewing PR's.

Cheers
Randy

**Comment by jchristn** [comment]
Thanks Randy, this is helpful.  Not the solution I was hoping for, but it
works.  I appreciate you getting back to me!
